#!/usr/bin/env bash

output=eDP-1
brightness=$(xrandr --verbose | grep Brightness | awk '{printf "%d", $2*100}')

echo $brightness

set_brightness() {
    xrandr --output $output --brightness $(echo $1 | awk '{printf "%0.2f", $1/100}' )
}

case $BLOCK_BUTTON in
    4) set_brightness $((brightness + 10 ))
        ;; # scroll up

    5) set_brightness $((brightness - 10 ))
        ;; # scroll down
esac
