#!/usr/bin/env bash

utilisation=$(mpstat | awk '$12 ~ /[0-9.]+/ { print 100 - $12"%" }')
temperature_path=/sys/devices/platform/coretemp.0/hwmon/hwmon*/temp1_input
load="↑ $(awk '{print $1}' /proc/loadavg)"
temperature=$(($(cat $temperature_path)/1000))°C

echo $utilisation $load $temperature 
