#!/usr/bin/env bash

output=eDP-1
brightness=?

get_brighntess() {
    brightness=$(xrandr --verbose | grep -m 1 Brightness | awk '{printf "%d", $2*100}')
}

set_brightness() {
    xrandr --output $output --brightness $(echo $1 | awk '{printf "%0.2f", $1/100}' )
    brightness=$1
}

get_brighntess

case $BLOCK_BUTTON in
    4) set_brightness $((brightness + 10 ))
        ;; # scroll up

    5) set_brightness $((brightness - 10 ))
        ;; # scroll down
esac

echo $brightness
